#! /g/ssli/sw/roylu/bin/python3

import os
import json

from utils import *
from config import *
import portalocker

hostname = os.environ['HOSTNAME'].split('.')[0]
os.makedirs(gpu_info_dir, exist_ok=True)

try:
    gpu_info_path = os.path.join(gpu_info_dir, hostname) 
    stdout = run_cmd(['/usr/bin/nvidia-smi -x -q | /g/ssli/sw/roylu/bin/xml2json'], timeout=10)
    gpus = json.loads(stdout)
    f = open(gpu_info_path, 'w')
    portalocker.lock(f, portalocker.LOCK_EX | portalocker.LOCK_NB)
    json.dump(gpus, f)
    f.flush()
    os.fsync(f.fileno())
    #with portalocker.Lock(gpu_info_path, 'w', timeout=1) as f:
    #    json.dump(gpus, f)
    #    f.flush()
    #    os.fsync(f.fileno())
except Exception as e:
    print('[Error]', e)

finally:
    portalocker.unlock(f)
